#Configuracion de SICP Via
#Sun Apr 19 16:12:51 PYT 2026
teclado.CATEGORIA_9=SHIFT+F9
teclado.CATEGORIA_8=SHIFT+F8
teclado.ROJO=CTRL+F8
teclado.BOMBERO=CTRL+F4
teclado.AMBULANCIA=CTRL+F3
teclado.EFECTIVO=CTRL+F1
sistema.version=1
teclado.POLICIA=CTRL+F5
teclado.EXENTO=CTRL+F6
teclado.CATEGORIA_3=SHIFT+F3
teclado.CATEGORIA_2=SHIFT+F2
teclado.CATEGORIA_1=SHIFT+F1
teclado.CATEGORIA_10=SHIFT+F10
teclado.POS=CTRL+F2
teclado.CATEGORIA_7=SHIFT+F7
teclado.VERDE=CTRL+F9
teclado.CATEGORIA_6=SHIFT+F6
teclado.CATEGORIA_5=SHIFT+F5
teclado.NOMINAR=CTRL+F7
teclado.CATEGORIA_4=SHIFT+F4
